spring:
  application:
    name: shuzimali-user-service
  rabbitmq:
    host: 192.168.238.133
    port: 5672
    virtual-host: shuzimali
    username: shuzimali
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000

  # 日志配置
  logging:
    level:
      com.alipay.shardingjdbc: info

  ### 本配置文件仅用于本地开发环境使用 ###
  # spring输出颜色
  output:
    ansi:
      enabled: ALWAYS

  # 配置真实数据源名称
  shardingsphere:
    datasource:
      names: ds0,ds1,ds2

      # 配置第1个数据源
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.238.133:3306/szml_users
        username: root
        password: "123456"

      # 配置第2个数据源
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.238.133:3306/szml_users_0
        username: root
        password: "123456"

      # 配置第3个数据源
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.238.133:3306/szml_users_1
        username: root
        password: "123456"

    rules:
      sharding:
        sharding-algorithms:
          database-line:
            type: INLINE
            props:
              algorithm-expression: ds$->{user_id % 3}
        # 定义哪一个列用于生成主键
        tables:
          users:
            key-generate-strategy:
              column: user_id
            # 定义employee表哪个是分片字段, 这里按主键字段ID
            database-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: database-line

        # 默认主键生成策略采用snowflake
        default-key-generate-strategy:
          xxx: snowflake

        # SNOWFLAKE
        key-generators:
          snowflake:
            type: SNOWFLAKE
            # 机器唯一标识
            props:
              worker-id: 666

    # 显示分库分表后执行的SQL语句
    props:
      sql-show: true
szml:
  jwt:
    location: classpath:shuzimali.user.jks
    alias: shuzimali
    password: 123456
    tokenTTL: 30m
  swagger:
    title: "用户服务接口文档"
    package: com.shuzimali.user.controller
rocketmq:
  name-server: 192.168.238.133:9876
  producer:
      group: shuzimali-user-service
      send-message-timeout: 5000